//
// BaseApiResponseClientModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct BaseApiResponseClientModel: Codable {

    public var responseObject: ClientModel?
    public var isSucceeded: Bool?
    public var message: String?

    public init(responseObject: ClientModel?, isSucceeded: Bool?, message: String?) {
        self.responseObject = responseObject
        self.isSucceeded = isSucceeded
        self.message = message
    }

    public enum CodingKeys: String, CodingKey { 
        case responseObject = "ResponseObject"
        case isSucceeded = "IsSucceeded"
        case message = "Message"
    }


}

