//
// BaseApiResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct BaseApiResponse: Codable {

    public var isSucceeded: Bool?
    public var message: String?

    public init(isSucceeded: Bool?, message: String?) {
        self.isSucceeded = isSucceeded
        self.message = message
    }

    public enum CodingKeys: String, CodingKey { 
        case isSucceeded = "IsSucceeded"
        case message = "Message"
    }


}

