//
// ClientModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ClientModel: Codable {

    public var _id: String?
    public var email: String?
    public var phoneNumber: String?

    public init(_id: String?, email: String?, phoneNumber: String?) {
        self._id = _id
        self.email = email
        self.phoneNumber = phoneNumber
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "Id"
        case email = "Email"
        case phoneNumber = "PhoneNumber"
    }


}

