//
// ClientDocumentsModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Документы клиента */

public struct ClientDocumentsModel: Codable {

    /** Паспорт */
    public var passport: RussianFederationPassportModel?

    public init(passport: RussianFederationPassportModel?) {
        self.passport = passport
    }

    public enum CodingKeys: String, CodingKey { 
        case passport = "Passport"
    }


}

