//
// LoginResultModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct LoginResultModel: Codable {

    public enum Result: String, Codable { 
        case error = "Error"
        case alreadyAuthenticated = "AlreadyAuthenticated"
        case unSuccessfulAttempt = "UnSuccessfulAttempt"
        case emailNotConfirmed = "EmailNotConfirmed"
        case successfulLogin = "SuccessfulLogin"
        case needConfirmation = "NeedConfirmation"
        case userDeactivated = "UserDeactivated"
    }
    public var result: Result?
    public var tokenId: String?

    public init(result: Result?, tokenId: String?) {
        self.result = result
        self.tokenId = tokenId
    }

    public enum CodingKeys: String, CodingKey { 
        case result = "Result"
        case tokenId = "TokenId"
    }


}

