//
// RussianFederationPassportModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RussianFederationPassportModel: Codable {

    /** Кем выдан */
    public var issuedBy: String?
    /** Дата выдачи */
    public var issueDate: Date?
    /** Местро рождения */
    public var birthPlace: String?
    /** Серия паспорта */
    public var series: String?
    /** Номер */
    public var number: String?
    /** Дата рождения */
    public var birthDate: Date?
    /** Имя */
    public var name: String?
    /** Фамилия */
    public var surname: String?
    /** Отчество */
    public var patronymic: String?

    public init(issuedBy: String?, issueDate: Date?, birthPlace: String?, series: String?, number: String?, birthDate: Date?, name: String?, surname: String?, patronymic: String?) {
        self.issuedBy = issuedBy
        self.issueDate = issueDate
        self.birthPlace = birthPlace
        self.series = series
        self.number = number
        self.birthDate = birthDate
        self.name = name
        self.surname = surname
        self.patronymic = patronymic
    }

    public enum CodingKeys: String, CodingKey { 
        case issuedBy = "IssuedBy"
        case issueDate = "IssueDate"
        case birthPlace = "BirthPlace"
        case series = "Series"
        case number = "Number"
        case birthDate = "BirthDate"
        case name = "Name"
        case surname = "Surname"
        case patronymic = "Patronymic"
    }


}

